baseURL: "https://purduearc.com"
languageCode: "en-us"
title: "Purdue ARC"
pygmentsstyle: 'monokai'
metaDataFormat: yaml
sectionPagesMenu: "main"
email: "purdueautonomy@gmail.com"
params:
  description: Gain real-world experience through building robot hardware and software, while solving state-of-the-art robotics problems.
  images:
  - images/logos/arc-logo-abbrev.png
  title: ARC Home 

# Theme settings
theme: novela
paginate: 2 
social:
  twitter: "https://twitter.com/purduerobotics"
  github: "https://github.com/purdue-arc"
  instagram: "https://www.instagram.com/purdue.arc"
  linkedin: "https://www.linkedin.com/company/purdue-arc"
  youtube: "https://www.youtube.com/channel/UCXr3FEZwfZ2gQgtgLHQkeBA"
taxonomies:
  series: series
  author: authors
